"""
This type stub file was generated by pyright.
"""

from pyphoplacecellanalysis.External.breeze_style_sheets import breeze_resources as breeze

"""
This type stub file was generated by pyright.
"""
