"""
This type stub file was generated by pyright.
"""

import pandas as pd
from datetime import datetime
from typing import Dict, Optional
from pyphocorehelpers.function_helpers import function_attributes

class FilesystemMetadata:
    """ helps with accessing cross-platform filesystem metadata
    
    
    from pyphocorehelpers.Filesystem.metadata_helpers import FilesystemMetadata
    """
    @staticmethod
    def get_last_modified_time(file_path: str) -> datetime:
        """
        Returns the last modified time of a file.

        :param file_path: The path to the file.
        :return: The last modified time as a datetime object.
        """
        ...
    
    @staticmethod
    def get_creation_time(file_path: str) -> datetime:
        """
        Returns the creation time of a file.

        :param file_path: The path to the file.
        :return: The creation time as a datetime object.
        """
        ...
    
    @staticmethod
    def get_file_size_GB(file_path: str) -> float:
        """
        Returns the size of a file in Gigabytes (GB).

        :param file_path: The path to the file.
        :return: The file size in Gigabytes (GB)
        """
        ...
    


def get_file_metadata(path, round_size_decimals: int = ...) -> Optional[Dict]:
    ...

@function_attributes(short_name=None, tags=['filesystem', 'metadata', 'creation_time', 'modification_time', 'datetime', 'files'], input_requires=[], output_provides=[], uses=[], used_by=[], creation_date='2023-06-07 02:16', related_items=[])
def get_files_metadata(paths) -> pd.DataFrame:
    """
    Get the metadata (modification time, creation time, and file size) for each file specified by a list of pathlib.Path objects.
    :param paths: A list of pathlib.Path objects representing the file paths.
    :return: A pandas DataFrame with columns for path, modification time, creation time, and file size.
    """
    ...

