"""
This type stub file was generated by pyright.
"""

from sys import platform

if platform == "linux" or platform == "linux2":
    def reveal_in_linux_file_manager(path: str) -> None:
        ...
    
else:
    def reveal_in_mac_file_manager(path: str) -> None:
        ...
    
def reveal_in_system_file_manager(path): # -> None:
    """ call to reveal a file in the system file browser. Currently only known to work on windows
    
    Usage:
        from pyphocorehelpers.Filesystem.open_in_system_file_manager import reveal_in_system_file_manager
        reveal_in_system_file_manager(r'R:\data\Output\2022-07-11\2006-6-07_11-26-53\maze2')
    """
    ...

