ruleDirs:
- H:\TEMP\Spike3DEnv_ExploreUpgrade\Spike3DWorkEnv\Spike3D\pho\ast-grep/rules
testConfigs:
- testDir: H:\TEMP\Spike3DEnv_ExploreUpgrade\Spike3DWorkEnv\Spike3D\pho\ast-grep\rule-tests
utilDirs:
- H:\TEMP\Spike3DEnv_ExploreUpgrade\Spike3DWorkEnv\Spike3D\pho\ast-grep\utils