# Form implementation generated from reading ui file 'c:\Users\pho\repos\pyPhoPlaceCellAnalysis\src\pyphoplacecellanalysis\GUI\Qt\PlacefieldVisualSelectionWidgetBase.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_rootForm(object):
    def setupUi(self, rootForm):
        rootForm.setObjectName("rootForm")
        rootForm.resize(100, 116)
        rootForm.setStyleSheet("background-color: rgb(71, 58, 46);\n"
"border-color: rgb(207, 207, 207);\n"
"background-color: rgba(71, 65, 60, 180);\n"
"color: rgb(244, 244, 244);\n"
"border-color: rgb(0, 0, 0);")
        self.gridLayout = QtWidgets.QGridLayout(rootForm)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(rootForm)
        self.groupBox.setMaximumSize(QtCore.QSize(160, 160))
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(2, 0, 2, 4)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.btnColorButton = ColorButton(self.groupBox)
        self.btnColorButton.setMinimumSize(QtCore.QSize(24, 24))
        self.btnColorButton.setText("")
        self.btnColorButton.setObjectName("btnColorButton")
        self.verticalLayout_2.addWidget(self.btnColorButton)
        self.chkbtnPlacefield = QtWidgets.QToolButton(self.groupBox)
        self.chkbtnPlacefield.setCheckable(True)
        self.chkbtnPlacefield.setChecked(False)
        self.chkbtnPlacefield.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.chkbtnPlacefield.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.chkbtnPlacefield.setObjectName("chkbtnPlacefield")
        self.verticalLayout_2.addWidget(self.chkbtnPlacefield)
        self.chkbtnSpikes = QtWidgets.QToolButton(self.groupBox)
        self.chkbtnSpikes.setCheckable(True)
        self.chkbtnSpikes.setChecked(False)
        self.chkbtnSpikes.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.chkbtnSpikes.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.chkbtnSpikes.setObjectName("chkbtnSpikes")
        self.verticalLayout_2.addWidget(self.chkbtnSpikes)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(rootForm)
        QtCore.QMetaObject.connectSlotsByName(rootForm)

    def retranslateUi(self, rootForm):
        _translate = QtCore.QCoreApplication.translate
        rootForm.setWindowTitle(_translate("rootForm", "Form"))
        self.groupBox.setTitle(_translate("rootForm", "pf[i]"))
        self.pushButton.setText(_translate("rootForm", "Title"))
        self.chkbtnPlacefield.setText(_translate("rootForm", "pf"))
        self.chkbtnSpikes.setText(_translate("rootForm", "spikes"))
from pyqtgraph.widgets.ColorButton import ColorButton
