# Form implementation generated from reading ui file 'c:\Users\pho\repos\pyPhoPlaceCellAnalysis\src\pyphoplacecellanalysis\GUI\Qt\PlacefieldVisualSelectionWidget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.btnColorButton = QtWidgets.QPushButton(self.groupBox)
        self.btnColorButton.setMinimumSize(QtCore.QSize(24, 24))
        self.btnColorButton.setText("")
        self.btnColorButton.setObjectName("btnColorButton")
        self.verticalLayout_2.addWidget(self.btnColorButton)
        self.chkbtnPlacefield = QtWidgets.QToolButton(self.groupBox)
        self.chkbtnPlacefield.setCheckable(True)
        self.chkbtnPlacefield.setChecked(False)
        self.chkbtnPlacefield.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.chkbtnPlacefield.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.chkbtnPlacefield.setObjectName("chkbtnPlacefield")
        self.verticalLayout_2.addWidget(self.chkbtnPlacefield)
        self.chkbtnSpikes = QtWidgets.QToolButton(self.groupBox)
        self.chkbtnSpikes.setCheckable(True)
        self.chkbtnSpikes.setChecked(False)
        self.chkbtnSpikes.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.chkbtnSpikes.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.chkbtnSpikes.setObjectName("chkbtnSpikes")
        self.verticalLayout_2.addWidget(self.chkbtnSpikes)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Title"))
        self.chkbtnPlacefield.setText(_translate("Form", "pf"))
        self.chkbtnSpikes.setText(_translate("Form", "spikes"))
