# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\pyPhoPlaceCellAnalysis\src\pyphoplacecellanalysis\GUI\Qt\ZoomAndNavigationSidebarControls\Spike3DRasterLeftSidebarControlBarBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_leftSideToolbarWidget(object):
    def setupUi(self, leftSideToolbarWidget):
        leftSideToolbarWidget.setObjectName("leftSideToolbarWidget")
        leftSideToolbarWidget.resize(94, 840)
        leftSideToolbarWidget.setStyleSheet("background-color: rgb(71, 58, 46);\n"
"border-color: rgb(207, 207, 207);\n"
"background-color: rgba(71, 65, 60, 180);\n"
"color: rgb(244, 244, 244);\n"
"border-color: rgb(0, 0, 0);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(leftSideToolbarWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(leftSideToolbarWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(leftSideToolbarWidget)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.verticalLayout.addWidget(self.doubleSpinBox_4)
        self.label_5 = QtWidgets.QLabel(leftSideToolbarWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(leftSideToolbarWidget)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.verticalLayout.addWidget(self.doubleSpinBox_5)
        self.label_6 = QtWidgets.QLabel(leftSideToolbarWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(leftSideToolbarWidget)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.verticalLayout.addWidget(self.doubleSpinBox_6)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(leftSideToolbarWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalScrollBar_2.sizePolicy().hasHeightForWidth())
        self.verticalScrollBar_2.setSizePolicy(sizePolicy)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.verticalLayout.addWidget(self.verticalScrollBar_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.verticalSlider_2 = QtWidgets.QSlider(leftSideToolbarWidget)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setInvertedAppearance(False)
        self.verticalSlider_2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.verticalLayout.addWidget(self.verticalSlider_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(leftSideToolbarWidget)
        QtCore.QMetaObject.connectSlotsByName(leftSideToolbarWidget)

    def retranslateUi(self, leftSideToolbarWidget):
        _translate = QtCore.QCoreApplication.translate
        leftSideToolbarWidget.setWindowTitle(_translate("leftSideToolbarWidget", "Form"))
        self.label_4.setText(_translate("leftSideToolbarWidget", "TextLabel"))
        self.label_5.setText(_translate("leftSideToolbarWidget", "TextLabel"))
        self.label_6.setText(_translate("leftSideToolbarWidget", "TextLabel"))
