"""
This type stub file was generated by pyright.
"""

import sys
from importlib.metadata import PackageNotFoundError, version
from importlib_metadata import PackageNotFoundError, version

if sys.version_info[: 2] >= (3, 8):
    ...
else:
    ...
dist_name = ...
__version__ = ...
