"""
This type stub file was generated by pyright.
"""

def freeze(d): # -> frozenset[tuple[Any, Any]] | tuple[Any, ...]:
    """ recursively freezes dicts with nested dict/list elements so they may be hashed """
    ...

def get_hash_tuple(a_dict, included_keys=...): # -> tuple[Any, ...]:
    """ Helps in hashing a dictionary by flattening it to a flat list of its keys and values, and then converting it into a tuple (which is what the hash function expects). """
    ...

def hash_dictionary(a_dict): # -> int:
    """ Hashes a dictionary from its keys and values. All members must be hashable themselves. """
    ...

