"""
This type stub file was generated by pyright.
"""

class WrappingPerformanceTimer:
    """ TODO: Doesn't quite work. Doesn't return the contents of its body which it should.
    
    Examples:
        with WrappingPerformanceTimer('Saving 2D Placefield image out to "{}"...'.format(active_plot_filepath), begin_line_ending='...', finished_message='done.'):
            for aFig in active_figures:
                aFig.savefig(active_plot_filepath)
    """
    def __init__(self, begin_string, begin_line_ending=..., finished_message=..., finished_line_ending=..., returns_string: bool = ..., enable_print: bool = ...) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    
    @classmethod
    def print_generic_progress_message(cls, begin_string, begin_line_ending, returns_string, enable_print): # -> str | None:
        ...
    


