"""
This type stub file was generated by pyright.
"""

"""

You can use `pd.describe_option()` to see the various customization options you can set for pandas

"""
def set_pho_preferences(is_concise=...): # -> None:
    """ Sets Pho Hale's general preferences for Jupyter Notebooks
    
    Includes increasing the number of rows/columns displayed for Pandas dataframes, and setting the numpy print options to be full-width for the jupyter notebook.
    """
    ...

def set_pho_preferences_verbose(): # -> None:
    ...

def set_pho_preferences_concise(): # -> None:
    ...

def set_pho_pandas_display_preferences(is_concise=...): # -> None:
    ...

def set_pho_numpy_display_preferences(is_concise=...): # -> None:
    ...

