% Takes the temporary .mat file output generated by the
% PhoPY3DPythonAnalysis-ipgany.ipynb Jupyter notebook and plots it
load('C:\Users\Pho\repos\PhoPy3DPositionAnalysis2021\output\all_spike_list_testing.mat')
figure(1)
clf
num_cells = length(spike_positions_list); % 92

layout = tiledlayout(23,4);
for curr_cell_index = 1:92
%    subplot(23, 4, curr_cell_index)
%     curr_cell_index = 43;
    nexttile;
    curr_cell_spikes = (spike_positions_list{curr_cell_index});
    scatter(curr_cell_spikes(1,:), curr_cell_spikes(2,:), 0.2);
    title(sprintf('Cell[%d]', curr_cell_index))
    xlim([0, 650])
    ylim([150, 265])
    xticks([])
    yticks([])
    box("on")
    %hold on;
%     curr_cell_index = 44;
%     curr_cell_spikes = (spike_positions_list{curr_cell_index});
%     scatter(curr_cell_spikes(1,:), curr_cell_spikes(2,:), 0.2);
end
% legend()
layout.TileSpacing = 'none';
%layout.TileSpacing = 'compact';
layout.Padding = 'compact';