name: GPT Commit Summary between Date Range
# Summary: This action will write a comment about every commit in a date range, 
# as well as generate a summary for every file that was modified and add it to the
# review page, compile a PR summary from all commit summaries and file diff 
# summaries, and delete outdated code review comments
on:
  workflow_dispatch:
    inputs:
      start_date:
        description: "Start date for the action"
        required: true
        default: "2024-12-29"
      end_date:
        description: "End date for the action"
        required: true
        default: "2025-01-06"

jobs:
  summarize_changes:
    runs-on: ubuntu-latest
    permissions: write-all  # Some repositories need this line

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Call Summarize Changes Action
        uses: CommanderPho/gpt-commit-summarizer@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}
